#!/bin/sh

primary=$(xrandr | grep primary | awk '{print $1}')
display=$(xrandr | grep connected | awk 'BEGIN { ORS=" " }; {print $1}' | sed 's/ /\\n/g')
output=$(printf $display | dmenu -i -p "Display mode")

res=1366x768

getaspectratio() {
	width=$(echo $res | sed 's/x.*//')
	height=$(echo $res | sed 's/.*x//')

	if [ "$height" -gt "$width" ]; then 
		dividend=$height
		divisor=$width
	else
		dividend=$width
		divisor=$height
	fi


	while [ "$divisor" -gt 0 ]; do
		modulo=$(($dividend%$divisor))
		dividend=$divisor
		divisor=$modulo
		gcd=$dividend
	done

	widthaspect=$(($width/$gcd))
	heightaspect=$(($height/$gcd))
	aspectratio=$widthaspect:$heightaspect
}

getaspectratio
echo $aspectratio

if [ "$output" ]; then
	fin=$(printf "$display" | awk 'BEGIN { ORS=" " }; {print $1}' | sed '/'$output'/s/.*'$output' \([^ ][^ ]*\)[ ]*.*/\1/')
	# TODO:
	# Create an if statement to see if last item has been chosen.
	# Or turn $display into an array.
	resolutions=$(xrandr | awk '/'$output'/{v=1}/'$fin'/{v=0}v' | sed -n '1!p' | sort -n -r | awk 'BEGIN { ORS=" " }; {print $1}' | sed 's/ /\\n/g') 2>/dev/null
	echo $resolutions
	if [ "$resolutions" = "" ];then
		printf "No resolutions found" | dmenu -p "Resolutions"
		exit
	fi
else
	exit
fi

res=$(printf $resolutions | dmenu -i -p "Resolutions")
if [ "${#res[*]}" -gt 6 ]; then
	if [ "$output" = "$primary" ]; then
#		echo primary
		xrandr --output $output --mode $res
		# Select screen position
	else
#		echo secondary
		pos=$(printf "left-of\\nright-of\\nabove\\nbelow\\nsame-as\\noff" | dmenu -i -p "Position")
		if [ "$pos" = "off" ]; then
			xrandr --output $output --$pos
		elif [ "$pos" != "off" ]; then
			xrandr --output $output --mode $res --$pos $primary
		fi
	fi
else
	exit
fi

# Auto config for broken display
[ "$(printf "No\\nYes" | dmenu -i -p "Auto config?")" = "Yes" ] && xrandr --output $output --auto
