.TH CONFIG_DISPLAYS 1 2020-06-11 GNU "User Commands"

.SH NAME
config_displays \- configures available displays
.SH SYNOPSIS
.SY config_displays
.YS

.SH DESCRIPTION
.B config_displays
configures displays made available through 
.B xrandr
and presents options to the user via 
.B dmenu
if installed.

.SG  BUGS
.TP
.SS "Reporting bugs"
Submit bug reports to the issues section at
.UR https://github.com/WhaleJ84/config_displays
.UE .

.SH AUTHORS
James Whale (james@james-whale.com)

.SH SEE ALSO
.BR dmenu (1),
.BR xrandr (1)
