#!/bin/sh

getdefaults(){
	displays=$(xrandr | grep connected | awk 'BEGIN { ORS=" " }; {print $1}' | sed 's/ /\\n/g')
	primary=$(xrandr | grep primary | awk '{print $1}')
	output=$primary
	getnextoutput
	primaryprefres=$(xrandr | awk '/'$output'/{v=1}/'$nextoutput'/{v=0}v' | sed -n '1!p' | grep + | awk '{print $1}')
	query=$primaryprefres
	getaspectratio
	primaryprefratio=$aspectratio
}

getnextoutput(){
	nextoutput=$(printf "$displays" | awk 'BEGIN { ORS=" " }; {print $1}' | sed '/'$output'/s/.*'$output' \([^ ][^ ]*\)[ ]*.*/\1/') 2>/dev/null
}

getoutputresolutions(){
	getnextoutput
	outputresolutions=$(xrandr | awk '/'$output'/{v=1}/'$nextoutput'/{v=0}v' | sed -n '1!p' | awk '{print $1}')
	if [ "$outputresolutions" = "" ]; then
		printf "No resolutions found" | dmenu -p "Resolutions"
		exit
	fi
	query=$(xrandr | awk '/'$output'/{v=1}/'$nextoutput'/{v=0}v' | sed -n '1!p' | grep + | awk '{print $1}')
	if [ "$query" = "" ]; then
		query=$(echo $outputresolutions | head -1 | awk '{print $1}')
	fi
	getaspectratio
	preferredratio=$aspectratio
}

sanitiseforprintf(){
	dmenuitems=$(echo $dmenuitems | sed 's/ /\n/g'  | awk 'BEGIN { ORS=" " }; {print $1}' | sed 's/ /\\n/g')
}

getaspectratio() {
	width=$(echo $query | sed 's/x.*//')
	height=$(echo $query | sed 's/.*x//' | awk '{gsub("[^[:digit:]]+"," "); print $1}') 

	if [ "$height" -gt "$width" ]; then 
		dividend=$height
		divisor=$width
	else
		dividend=$width
		divisor=$height
	fi

	while [ "$divisor" -gt 0 ]; do
		modulo=$(($dividend%$divisor))
		dividend=$divisor
		divisor=$modulo
		gcd=$dividend
	done

	widthaspect=$(($width/$gcd))
	heightaspect=$(($height/$gcd))
	aspectratio=$widthaspect:$heightaspect
}

getrelativeresolutions(){
	getoutputresolutions
	for line in $outputresolutions; do
		query=$line
		getaspectratio
		if [ "$aspectratio" = "$preferredratio" ]; then
			relativeresolutions="$relativeresolutions$line"\\n
		fi
		dmenuitems="$relativeresolutions"All
	done
}

selectoutput(){
getdefaults
output=$(printf $displays | dmenu -i -p "Outputs")
if [ "$output" = "" ]; then
	exit
fi
}

selectresolution(){
res=$(printf $dmenuitems | dmenu -i -p "Resolutions")
if [ "${#res[*]}" -gt 6 ]; then
	if [ "$output" = "$primary" ]; then
		xrandr --output $output --mode $res
	else
		pos=$(printf "left-of\\nright-of\\nabove\\nbelow\\nsame-as\\noff" | dmenu -i -p "Position")
		if [ "$pos" = "off" ]; then
			xrandr --output $output --$pos
		elif [ "$pos" != "off" ]; then
			xrandr --output $output --mode $res --$pos $primary
		fi
	fi
elif [ "$res" = "All" ]; then
	getoutputresolutions
	dmenuitems=$outputresolutions
	sanitiseforprintf
	selectresolution
else
	exit
fi
}

selectoutput

getrelativeresolutions
sanitiseforprintf
selectresolution


# Auto config for broken display
[ "$(printf "No\\nYes" | dmenu -i -p "Auto config?")" = "Yes" ] && xrandr --output $output --auto
