#!/bin/sh

#set -x

getdefaults(){
	displays=$(xrandr | grep connected | awk 'BEGIN { ORS=" " }; {print $1}' | sed 's/ /\\n/g')
	primary=$(xrandr | grep primary | awk '{print $1}')
	output=$primary
	getnextoutput
	primaryprefres=$(xrandr | awk '/'$output'/{v=1}/'$nextoutput'/{v=0}v' | sed -n '1!p' | grep + | awk '{print $1}')
	query=$primaryprefres
	getaspectratio
	primaryprefratio=$aspectratio
}

getnextoutput(){
	nextoutput=$(printf "$displays" | awk 'BEGIN { ORS=" " }; {print $1}' | sed '/'$output'/s/.*'$output' \([^ ][^ ]*\)[ ]*.*/\1/')
}

getoutputresolutions(){
	getnextoutput
	outputresolutions=$(xrandr | awk '/'$output'/{v=1}/'$nextoutput'/{v=0}v' | sed -n '1!p' | awk '{print $1}')
	query=$(xrandr | awk '/'$output'/{v=1}/'$nextoutput'/{v=0}v' | sed -n '1!p' | grep + | awk '{print $1}')
	if [ "$query" = "" ]; then
		echo "No preferred resolution. Using first result."
		query=$(echo $outputresolutions | head -1 | awk '{print $1}')
	fi
	getaspectratio
}

sanitiseforprintf(){
	dmenuitems=$(echo $dmenuitems | sed 's/ /\n/g'  | awk 'BEGIN { ORS=" " }; {print $1}' | sed 's/ /\\n/g')
}

getaspectratio() {
	width=$(echo $query | sed 's/x.*//')
	height=$(echo $query | sed 's/.*x//')

	if [ "$height" -gt "$width" ]; then 
		dividend=$height
		divisor=$width
	else
		dividend=$width
		divisor=$height
	fi

	while [ "$divisor" -gt 0 ]; do
		modulo=$(($dividend%$divisor))
		dividend=$divisor
		divisor=$modulo
		gcd=$dividend
	done

	widthaspect=$(($width/$gcd))
	heightaspect=$(($height/$gcd))
	aspectratio=$widthaspect:$heightaspect
}

getrelativeresolutions(){
	getoutputresolutions
	for line in $outputresolutions; do
		query=$line
		getaspectratio
		echo $aspectratio
		if [ "$aspectratio" = "$preferredratio" ]; then
			relativeresolutions=$relativeresolutions$line
		fi
		dmenuitems="$relativeresolutions"\\nAll
	done
}

getdefaults
output=$(printf $displays | dmenu -i -p "Display mode")

if [ "$output" ]; then
	if [ "$output" != "$primary" ]; then
		echo "Non-primary display. Getting default aspect ratio."	
	fi
	getrelativeresolutions
	sanitiseforprintf
	if [ "$dmenuitems" = "" ]; then
		printf "No resolutions found" | dmenu -p "Resolutions"
		exit
	fi
else
	exit
fi

res=$(printf $dmenuitems | dmenu -i -p "Resolutions")
if [ "$res" = "All" ]; then
	getoutputresolutions
	dmenuitems=$outputresolutions
	sanitiseforprintf
fi

res=$(printf $dmenuitems | dmenu -i -p "Resolutions")
if [ "${#res[*]}" -gt 6 ]; then
	if [ "$output" = "$primary" ]; then
		xrandr --output $output --mode $res
	else
		pos=$(printf "left-of\\nright-of\\nabove\\nbelow\\nsame-as\\noff" | dmenu -i -p "Position")
		if [ "$pos" = "off" ]; then
			xrandr --output $output --$pos
		elif [ "$pos" != "off" ]; then
			xrandr --output $output --mode $res --$pos $primary
		fi
	fi
else
	exit
fi

# Auto config for broken display
[ "$(printf "No\\nYes" | dmenu -i -p "Auto config?")" = "Yes" ] && xrandr --output $output --auto
#set +x
